;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	ace-jump-mode
	ace-jump-move
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	kill-rectangle
	org-self-insert-command
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	TeX-command-master
	c-electric-lt-gt
	ede-compile-project
	))
